// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/swipe": {
    params: {};
  };
  "/results": {
    params: {};
  };
  "/contacts": {
    params: {};
  };
  "/contacts/:contactId": {
    params: {
      "contactId": string;
    };
  };
  "/contacts/:contactId/edit": {
    params: {
      "contactId": string;
    };
  };
  "/contacts/:contactId/destroy": {
    params: {
      "contactId": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/swipe" | "/results" | "/contacts" | "/contacts/:contactId" | "/contacts/:contactId/edit" | "/contacts/:contactId/destroy";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/swipe.jsx": {
    id: "routes/swipe";
    page: "/swipe";
  };
  "routes/results.jsx": {
    id: "routes/results";
    page: "/results";
  };
  "layouts/sidebar.jsx": {
    id: "layouts/sidebar";
    page: "/contacts" | "/contacts/:contactId" | "/contacts/:contactId/edit" | "/contacts/:contactId/destroy";
  };
  "routes/contacts-index.jsx": {
    id: "routes/contacts-index";
    page: "/contacts";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contacts/:contactId";
  };
  "routes/edit-contact.jsx": {
    id: "routes/edit-contact";
    page: "/contacts/:contactId/edit";
  };
  "routes/destroy-contact.jsx": {
    id: "routes/destroy-contact";
    page: "/contacts/:contactId/destroy";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/swipe": typeof import("./app/routes/swipe.jsx");
  "routes/results": typeof import("./app/routes/results.jsx");
  "layouts/sidebar": typeof import("./app/layouts/sidebar.jsx");
  "routes/contacts-index": typeof import("./app/routes/contacts-index.jsx");
  "routes/contact": typeof import("./app/routes/contact.jsx");
  "routes/edit-contact": typeof import("./app/routes/edit-contact.jsx");
  "routes/destroy-contact": typeof import("./app/routes/destroy-contact.jsx");
};