// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/map": {
    params: {};
  };
  "/map/:locationId": {
    params: {
      "locationId": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/map" | "/map/:locationId";
  };
  "routes/intro.jsx": {
    id: "routes/intro";
    page: "/";
  };
  "routes/map.jsx": {
    id: "routes/map";
    page: "/map" | "/map/:locationId";
  };
  "layouts/detail-panel.jsx": {
    id: "layouts/detail-panel";
    page: "/map/:locationId";
  };
  "routes/location-detail.jsx": {
    id: "routes/location-detail";
    page: "/map/:locationId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/intro": typeof import("./app/routes/intro.jsx");
  "routes/map": typeof import("./app/routes/map.jsx");
  "layouts/detail-panel": typeof import("./app/layouts/detail-panel.jsx");
  "routes/location-detail": typeof import("./app/routes/location-detail.jsx");
};