// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/print": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/print";
  };
  "routes/index.jsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/print.js": {
    id: "routes/print";
    page: "/print";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/index": typeof import("./app/routes/index.jsx");
  "routes/print": typeof import("./app/routes/print.js");
};